### ISSUE TITLE
Task composeUp fails to execute because buildDockerImage is UP_TO_DATE and DOCKER_IMAGE is not set

### ISSUE THREAD

**Issue by todorinskiz** [xenit-eu/alfresco-docker-gradle-plugin#104]
### Plugins:
```
    id 'eu.xenit.docker-alfresco' version '5.0.2'
    id "eu.xenit.docker-compose" version '5.0.0'
```

### Steps to reproduce:
1. Run task `buildDockerImage`
2. Run task `composeUp`

#### Expected:
- Complete the task execution successfully
  - Task `buildDockerImage` is already `UP_TO_DATE`
  - Variable `DOCKER_IMAGE` is set
  - Task `composeUp` is executed successfully

#### Actual:
- Task fails because `DOCKER_IMAGE` variable is not set

### Cause Analysis
Likely to be caused by: https://github.com/xenit-eu/alfresco-docker-gradle-plugin/issues/96

### Output
```
10:57:55 AM: Executing task 'composeUp'...

> Task :stripAlfrescoWar UP-TO-DATE
> Task :applyAlfrescoAmp UP-TO-DATE
> Task :applyAlfrescoDE UP-TO-DATE
> Task :applyAlfrescoSM UP-TO-DATE
> Task :applyShareAmp NO-SOURCE
> Task :applyShareSM NO-SOURCE
> Task :stripShareWar NO-SOURCE
> Task :createDockerFile UP-TO-DATE
> Task :buildDockerImage UP-TO-DATE

> Task :composeUp
The DOCKER_IMAGE variable is not set. Defaulting to a blank string.
share uses an image, skipping
alfresco uses an image, skipping
The DOCKER_IMAGE variable is not set. Defaulting to a blank string.
```

**Comment by vierbergenlars** [comment]
This puts a `doLast` action on the `buildDockerImage` task: https://github.com/xenit-eu/alfresco-docker-gradle-plugin/blob/e9461aa44fb54bf2edc03b94d82b578bd1d36bcf/src/main/java/eu/xenit/gradle/docker/compose/DockerComposeConventionImpl.java#L46-L51

However, actions are not called when a task is UP-TO-DATE. So setting the environment variable is not executed in this case.

I think this can be fixed by instead of adding a `doLast` action to `buildDockerImage`, we can put a `doFirst` action on the applicable `composeXXX` tasks that will read the environment variables from the `DockerBuildImage` task here: https://github.com/xenit-eu/alfresco-docker-gradle-plugin/blob/e9461aa44fb54bf2edc03b94d82b578bd1d36bcf/src/main/java/eu/xenit/gradle/docker/compose/DockerComposeConventionImpl.java#L26-L34
Even when the task is `UP-TO-DATE`, the image ID can be retrieved, because it is cached and restored by `DockerBuildImage`.
