### ISSUE TITLE
ApplyAlfrescoAmp fails for alfresco records management amp

### ISSUE THREAD

**Issue by RVanhuysseXenit** [xenit-eu/alfresco-docker-gradle-plugin#180]
# Environment
gradle wrapper 6.7
eu.xenit.docker-alfresco 5.1.1
target alfresco 5.2.5
alfresco-rm-enterprise 2.6.0

# Scenario
Trying to install the alfresco-rm-enterprise amp in a generated docker image

# Observed behaviour
```
> Task :applyAlfrescoAmp FAILED
Deprecated features were used in this build, making it incompatible with alfresco-docker-plugin 6.0.
Use --warning-mode all to show individual deprecation warnings.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applyAlfrescoAmp'.
> java.nio.file.NoSuchFileException: /module.properties
```

# Expected behaviour
The amp is installed correctly and the docker image is generated

# Reproduction project:
https://github.com/xenit-eu/recordsManagementAmpBug

# Additional observations
* I downloaded and opened the rm artifact manually and it did contain an module.properties file in its root. The file itself seems valid.
* I've also encountered the same issue with alfresco 61.

**Comment by vierbergenlars** [comment]
I attached a debugger on the failing reproduction.
![2020-12-09-173034_1920x1080_scrot](https://user-images.githubusercontent.com/1194648/101657541-4d0fcb80-3a44-11eb-81d8-85e2dc2e5d16.png)

The failing "amp" file here is actually a jar (`com.google.code.gson:gson:2.3.1`).

The  the records-management AMP specifies a dependency on this jar. Since dependency resolution is transitive, the `alfrescoAmp` configuration contains these files as well, and we attempt to apply them as an amp (which fails of course).

```
$ ./gradlew dependencies --configuration alfrescoAmp
> Task :dependencies

------------------------------------------------------------
Root project - Reproduction project for docker-alfresco gradle plugin bug
------------------------------------------------------------

alfrescoAmp
+--- eu.xenit:alfresco-dynamic-extensions-repo-52:2.0.5
+--- eu.xenit.apix:apix-impl-52-amp:2.7.0
+--- eu.xenit.care4alf:care4alf-5x:2.3.0
\--- org.alfresco:alfresco-rm-enterprise-repo:2.6.0
     +--- com.google.code.gson:gson:2.3.1
     \--- org.alfresco:alfresco-rm-community-repo:2.6.0

A web-based, searchable dependency report is available by adding the --scan option.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 8s
1 actionable task: 1 executed
```

You can make it non-transitive in 2 ways:

1. Add `@amp` file-extension specifier (`alfrescoAmp "org.alfresco:alfresco-rm-enterprise-repo:2.6.0@amp"`) When an extension is specified, Gradle will not perform dependency resolution
2. Explicitly disable transitive dependency resolution: `alfrescoAmp("org.alfresco:alfresco-rm-enterprise-repo:2.6.0") { transitive = false }`

Nevertheless, I think it is a good idea to show at least the filename of the file that we failed to process so you have some indication on where to look.
