### ISSUE TITLE
Make it possible to disable modifying log4j.properties

### ISSUE THREAD

**Issue by thijslemmens** [xenit-eu/alfresco-docker-gradle-plugin#201]
I want to use the docker-alfresco plugin to publish a war. However, the plugin always creates a task to modify the log4j.properties:
https://github.com/xenit-eu/alfresco-docker-gradle-plugin/blob/2e271bf7217d8956b6b0846fec1c12ef915a9cb9/src/main/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPlugin.java#L149

This task serves to remove the File appender and to prefix logs with [ALFRESCO] or [SHARE]. This is mainly useful in Docker scenario's. It would be nice to have a flag not to create the task.

**Comment by vierbergenlars** [comment]
While working on this, I discovered that rewriting log4j.properties in docker images is broken since https://github.com/xenit-eu/alfresco-docker-gradle-plugin/commit/a24e6dd4bd75ceb5509f0374e855be99a7d69fff (released in 5.0.7), where it was moved to a separate task.

However, it is still being rewritten in Alfresco WARs that are also created by the plugin.

I have heard no complaints about that from anywhere about this. So maybe we can just scrap the feature completely?
