### ISSUE TITLE
Adjust image version check to fail when docker image does not contain Alfresco war

### ISSUE THREAD

**Issue by todorinskiz** [xenit-eu/alfresco-docker-gradle-plugin#230]
Skeleton images do not contain base Alfresco WAR, so when applying just the modules without the base WAR, we cannot build a proper Alfresco instance.

It would be nice if we could catch this case and decide what to do with it:
- We already have a base WAR defined in the dependencies, we can use that one to apply as an extra step
- Simply throw an exception

**Comment by vierbergenlars** [comment]
That's why you set `leanImage = false`, which will replace any existing files with the full unpacked WAR. This option is the default.

Additionally, I believe that during the docker build, we check the alfresco `WEB-INF/classes/alfresco/version.properties` file to determine if you are not trying to use a different base war version from the version in the image.

That should already result in an error when building the docker image.

**Comment by thijslemmens** [comment]
We did end up in using `leanImage = false` . This is indeed a user error.
The version check does not trigger a problem. Using `leanImage = true` with a skeleton image results in an image without the baseWar.
We can consider implementing something that would detect this situation and warn the user as an enhancement.
