### ISSUE TITLE
Do not automatically apply docker-compose plugin

### ISSUE THREAD

**Issue by thijslemmens** [xenit-eu/alfresco-docker-gradle-plugin#58]
We need to decouple because we are switching to separate containers for Alfresco and Share. We can still detect the plugin is applied and fill in the environment variables like we do now.

**Comment by tgeens** [comment]
Would be very nice, but is a breaking change ?
Can I suggest we add a deprecation warning first ?

**Comment by vierbergenlars** [comment]
Yes, this will be a breaking change, but it will be for the next major version of the plugin. Breaking changes are allowed in major versions.
We can not put deprecation warnings, because we cannot detect the difference between someone using the docker-compose plugin because it is applied by this plugin, or when someone applies the docker-compose plugin manually.

There will be a migration guide for 5.0 listing all the things you may have to change (and this is one of the more easy changes to make: https://github.com/xenit-eu/alfresco-docker-gradle-plugin/commit/2b6920c0818f238d5c0ceedf192992fd50371925#diff-938577e02279c57ddcc420c354fc40f9R3
